create table if not exists silver.fixtures (
    fixture_id      int primary key,
    league_id       int,
    season          int,
    round           text,
    kickoff         timestamptz,
    status_short    text,
    status_long     text,
    status_elapsed  int,
    referee         text,
    venue_id        int,
    venue_name      text,
    venue_city      text,
    home_team_id    int,
    home_team_name  text,
    away_team_id    int,
    away_team_name  text,
    home_winner     boolean,
    away_winner     boolean,
    goals_home      int,
    goals_away      int,
    ht_home         int,
    ht_away         int,
    ft_home         int,
    ft_away         int,
    et_home         int,
    et_away         int,
    pen_home        int,
    pen_away        int,
    loaded_at       timestamptz
);